// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let { data: { session } } = await supabase.auth.getSession()
    if (!session) {
      // Wait a tiny bit (100ms) and retry in case of a login/redirect race condition
      await new Promise(resolve => setTimeout(resolve, 100))
      const res = await supabase.auth.getSession()
      session = res.data.session
    }
    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
